Added code for date format identifier
klarEDA/klar-EDA pull request #25
Opened 2021-03-12 14:33 UTC by abh33

2021-03-12 17:40 UTC, Ask149 requested changes
Implement the format identifier function inside the `csv_preprocess.py` and add the tests inside a new file under `klareda/preprocess` directory ( with no main methods ). Rest of the implementation seems good. Thanks!

2021-03-19 03:59 UTC, Ask149 commented
@abh33 moving forward, please use 4 spaces indentation. Have updated the same in the PR. Thank you for your work.

2021-03-19 04:00 UTC, Ask149 approved these changes

2021-03-19 04:11 UTC, ishaanballal21 approved these changes

2021-03-19 04:11 UTC, merged